version: '3.8'

services:
  mysql:
    container_name: agendamento_db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: agendamentodb
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/data/mysql

volumes:
  mysql_data: